import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { readFileSync, writeFileSync, statSync, chmodSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Create a fresh Pharos Atlantic deployer wallet.
 *
 * Generates a new secp256k1 private key, derives the matching
 * EOA address, and writes a `.env` file (gitignored) at the
 * project root with the deployer key and address filled in.
 *
 * The script is idempotent: it refuses to overwrite an existing
 * `.env` so a real key is never silently discarded. Delete the
 * file first if you want a brand-new wallet.
 *
 * Security:
 *   - The private key is written only to `.env` (gitignored).
 *   - The script prints the **address** to stdout so the user can
 *     fund the wallet. The private key is never printed.
 *   - The file mode is set to `0o600` (owner read/write only)
 *     on POSIX filesystems. Windows ignores POSIX modes; use the
 *     OS ACL to restrict access on Windows.
 *
 * Usage:
 *   node tools/create-wallet.mjs
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = resolve(__dirname, "..");
const envPath = resolve(projectRoot, ".env");

if (statSync(envPath, { throwIfNoEntry: false })) {
  console.error(`error: ${envPath} already exists.`);
  console.error("Delete it first if you want a brand-new wallet.");
  process.exit(1);
}

const pk = generatePrivateKey();
const account = privateKeyToAccount(pk);

const envContent = [
  "# Generated by tools/create-wallet.mjs on " + new Date().toISOString(),
  "# Pharos Atlantic (chain id 688689)",
  "PHAROS_RPC_URL=https://atlantic.dplabs-internal.com",
  "PHAROS_CHAIN_ID=688689",
  "PHAROS_EXPLORER_URL=https://atlantic.pharosscan.xyz",
  "PHAROS_REGISTRY_ADDRESS=",
  "ROUTER_DEPLOYER_PRIVATE_KEY=" + pk,
  "ROUTER_DEPLOYER_ADDRESS=" + account.address,
  "",
].join("\n");

writeFileSync(envPath, envContent, { mode: 0o600 });
try {
  chmodSync(envPath, 0o600);
} catch {
  /* POSIX-only; Windows uses ACLs. */
}

const mode = (statSync(envPath).mode & 0o777).toString(8);
console.log("Wallet generated and saved to .env.");
console.log("");
console.log("=== PUBLIC ADDRESS (send PHRS here) ===");
console.log(account.address);
console.log("======================================");
console.log("");
console.log("File mode:", mode, "(0o600 = owner-only on POSIX)");
console.log("Private key length:", pk.length, "(expected 66 with 0x prefix)");
